server:
  port: ${SERVER_PORT:8006}
spring:
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 3000
    lettuce:
      pool.max-idle: 8 #连接池中最大空闲连接
      pool.min-idle: 1 #连接池中最小空闲连接
      pool.max-active: 8 #连接池最大连接数
      pool.max-wait: -1  #连接池最大阻塞等待时间，负值表示没有限制
minio:
  endpoint: ${MINIO_ENDPOINT:http://minio-storage-url.hdt.cosmoplat.com}
  accesskey: ${MINIO_ASSESSKEY:admin}
  secretkey: ${MINIO_SECRETKEY:12345678}
  bucket: ${MINIO_BUCKET:test}


oss:
  enabled: true
  type: MINIO
  endpoint: ${MINIO_ENDPOINT:http://minio-storage-url.hdt.cosmoplat.com}
  access-key: ${MINIO_ASSESSKEY:admin}
  secret-key: ${MINIO_SECRETKEY:12345678}
  default-bucket-name: ${MINIO_BUCKET:test-buckent}


aws:
  endPoint: http://oss.hd.cosmoplat.com
  accessKey: 9A5XWE4XM1S0FRT7V3ER
  secretKey: G9CUqloMoBj4DitayY7TWQpFeHHLMshpFFmmYxST
  region: us-east-2
  bucket: workshop-bucket
  minPartSize: 5242880